language: java
jobs:
  include:
    - jdk:
      - openjdk8
      - openjdk11
      - openjdk13
      - openjdk15
      - openjdk17
    - python:
      - 3.6
      - 3.7
      - 3.8
      - 3.9
      - 3.10
before_install:
  - pyenv shell
  - cd python
install:
  - pip install pytest-cov pytest codecov
script:
  - python setup.py install
  - py.test --cov-report term --cov=cogroo4py
after_success:
  - codecov