import java.io
import java.net
import javax.swing.tree
import jpype.protocol
import org.apache.log4j.lf5.viewer
import typing



class ConfigurationManager:
    def __init__(self, logBrokerMonitor: org.apache.log4j.lf5.viewer.LogBrokerMonitor, logTable: org.apache.log4j.lf5.viewer.LogTable): ...
    def reset(self) -> None: ...
    def save(self) -> None: ...
    @staticmethod
    def treePathToString(treePath: javax.swing.tree.TreePath) -> str: ...

class MRUFileManager:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    @staticmethod
    def createConfigurationDirectory() -> None: ...
    def getFile(self, int: int) -> typing.Any: ...
    def getInputStream(self, int: int) -> java.io.InputStream: ...
    def getMRUFileList(self) -> typing.List[str]: ...
    def moveToTop(self, int: int) -> None: ...
    def save(self) -> None: ...
    @typing.overload
    def set(self, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> None: ...
    @typing.overload
    def set(self, uRL: java.net.URL) -> None: ...
    def size(self) -> int: ...


class __module_protocol__(typing.Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.apache.log4j.lf5.viewer.configure")``.

    ConfigurationManager: typing.Type[ConfigurationManager]
    MRUFileManager: typing.Type[MRUFileManager]
