import java.util
import typing



class Prep:
    def __init__(self): ...
    def getMeaning(self) -> str: ...
    def getObjects(self) -> java.util.List[str]: ...
    def getPreposition(self) -> str: ...
    def setMeaning(self, string: str) -> None: ...
    def setObjects(self, string: str) -> None: ...
    def setPreposition(self, string: str) -> None: ...

class VerbPlusPreps:
    def __init__(self, list: java.util.List[Prep]): ...
    def findWord(self, string: str) -> Prep: ...

class Verbs:
    def __init__(self): ...
    def getVerb(self, string: str) -> VerbPlusPreps: ...
    def parseConfiguration(self) -> java.util.Map[str, VerbPlusPreps]: ...


class __module_protocol__(typing.Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.cogroo.tools.checker.rules.verbs")``.

    Prep: typing.Type[Prep]
    VerbPlusPreps: typing.Type[VerbPlusPreps]
    Verbs: typing.Type[Verbs]
