import java.util
import opennlp.tools.dictionary
import org.cogroo.analyzer
import org.cogroo.entities
import org.cogroo.text
import org.cogroo.tools.checker
import typing



class GovernmentChecker(org.cogroo.tools.checker.AbstractChecker):
    def __init__(self): ...
    def check(self, sentence: org.cogroo.text.Sentence) -> java.util.List[org.cogroo.entities.Mistake]: ...
    def findNouns(self, sentence: org.cogroo.text.Sentence) -> java.util.List[org.cogroo.text.Token]: ...
    def findPrep(self, sentence: org.cogroo.text.Sentence, token: org.cogroo.text.Token) -> org.cogroo.text.Token: ...
    def findVerb(self, sentence: org.cogroo.text.Sentence) -> org.cogroo.text.Token: ...
    def getIdPrefix(self) -> str: ...
    def getPriority(self) -> int: ...

class ParonymChecker(org.cogroo.tools.checker.AbstractChecker):
    def __init__(self, analyzer: org.cogroo.analyzer.Analyzer): ...
    def check(self, sentence: org.cogroo.text.Sentence) -> java.util.List[org.cogroo.entities.Mistake]: ...
    def getIdPrefix(self) -> str: ...
    def getPriority(self) -> int: ...

class PunctuationChecker(org.cogroo.tools.checker.AbstractTypedChecker):
    def __init__(self): ...
    def check(self, sentence: org.cogroo.entities.Sentence) -> java.util.List[org.cogroo.entities.Mistake]: ...
    def getIdPrefix(self) -> str: ...
    def getPriority(self) -> int: ...

class RepetitionChecker(org.cogroo.tools.checker.AbstractTypedChecker):
    def __init__(self): ...
    def check(self, sentence: org.cogroo.entities.Sentence) -> java.util.List[org.cogroo.entities.Mistake]: ...
    def getIdPrefix(self) -> str: ...
    def getPriority(self) -> int: ...

class SpaceChecker(org.cogroo.tools.checker.AbstractTypedChecker):
    def __init__(self, dictionary: opennlp.tools.dictionary.Dictionary): ...
    def check(self, sentence: org.cogroo.entities.Sentence) -> java.util.List[org.cogroo.entities.Mistake]: ...
    def getIdPrefix(self) -> str: ...
    def getPriority(self) -> int: ...


class __module_protocol__(typing.Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.cogroo.tools.checker.checkers")``.

    GovernmentChecker: typing.Type[GovernmentChecker]
    ParonymChecker: typing.Type[ParonymChecker]
    PunctuationChecker: typing.Type[PunctuationChecker]
    RepetitionChecker: typing.Type[RepetitionChecker]
    SpaceChecker: typing.Type[SpaceChecker]
